---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Puppet.
  package:
    name: "{{ puppet_package }}"
    state: present

- name: Add Puppet bin directory to $PATH.
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?{{ puppet_bin_path }}).*?)(["]*)$'
    line="PATH=\1\2:{{ puppet_bin_path }}\3"
    mode=0644

- name: Update Pupet Agentconfiguration
  ini_file:
    path: "{{ puppet_conf_path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: true
  with_items:
    - { section: "agent", option: "runinterval", value: "{{ puppet_agent_config_runinterval }}" }
    - { section: "agent", option: "environment", value: "{{ puppet_agent_config_environment }}" }
    - { section: "agent", option: "certname", value: "{{ puppet_agent_config_certname }}" }

# - name: Ensure "fav=lemonade is in section "[agent]" in specified file
#   community.general.ini_file:
#     path: "{{ puppet_conf_path }}"
#     section: agent
#     option: runinterval
#     value: "{{ puppet_conf_path }}"
#     mode: '0600'
#     backup: yes

- name: Ensure Puppet service is started and enabled at boot.
  service:
    name: "{{ puppet_service }}"
    state: "{{ puppet_service_state }}"
    enabled: "{{ puppet_service_enabled }}"
  when: puppet_service_manage
